# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import word_frequency

ob = word_frequency.MostCommonWords()


class Ui_BarGraph(object):

    def setup(self, MainWindow):
        MainWindow.setObjectName("BarGraph")
        MainWindow.resize(578, 816)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelUCTLogo = QtWidgets.QLabel(self.centralwidget)
        self.labelUCTLogo.setGeometry(QtCore.QRect(40, -40, 511, 301))
        self.labelUCTLogo.setText("")
        self.labelUCTLogo.setPixmap(QtGui.QPixmap("uct_original_logo.jpg"))
        self.labelUCTLogo.setObjectName("labelUCTLogo")
        self.lablelTextMostCommon = QtWidgets.QLabel(self.centralwidget)
        self.lablelTextMostCommon.setGeometry(QtCore.QRect(50, 200, 521, 131))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(6)
        self.lablelTextMostCommon.setFont(font)
        self.lablelTextMostCommon.setObjectName("lablelTextMostCommon")
        self.pushButtonPositive = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPositive.setGeometry(QtCore.QRect(160, 350, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(16)
        self.pushButtonPositive.setFont(font)
        self.pushButtonPositive.setStyleSheet("color: rgb(0, 0, 127);\n"
                                              "background-color: rgb(85, 255, 255);\n"
                                              "border-top-color: rgb(0, 0, 0);\n"
                                              "border-color: rgb(0, 0, 127);")
        self.pushButtonPositive.setObjectName("pushButtonPositive")
        self.pushButtonNeutral = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNeutral.setGeometry(QtCore.QRect(160, 550, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(16)
        self.pushButtonNeutral.setFont(font)
        self.pushButtonNeutral.setStyleSheet("color: rgb(0, 0, 127);\n"
                                             "background-color: rgb(85, 255, 255);")
        self.pushButtonNeutral.setObjectName("pushButtonNeutral")
        self.pushButtonNegative = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNegative.setGeometry(QtCore.QRect(160, 450, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(16)
        self.pushButtonNegative.setFont(font)
        self.pushButtonNegative.setStyleSheet("color: rgb(0, 0, 127);\n"
                                              "background-color: rgb(85, 255, 255);")
        self.pushButtonNegative.setObjectName("pushButtonNegative")
        self.labelImageNegative = QtWidgets.QLabel(self.centralwidget)
        self.labelImageNegative.setGeometry(QtCore.QRect(380, 450, 81, 71))
        self.labelImageNegative.setText("")
        self.labelImageNegative.setPixmap(QtGui.QPixmap("Very_sad_emoji_icon_png_large.png"))
        self.labelImageNegative.setScaledContents(True)
        self.labelImageNegative.setObjectName("labelImageNegative")
        self.labelImageNeutral = QtWidgets.QLabel(self.centralwidget)
        self.labelImageNeutral.setGeometry(QtCore.QRect(380, 550, 81, 71))
        self.labelImageNeutral.setText("")
        self.labelImageNeutral.setPixmap(QtGui.QPixmap("Neutral_Face_Emoji_large.png"))
        self.labelImageNeutral.setScaledContents(True)
        self.labelImageNeutral.setObjectName("labelImageNeutral")
        self.labelImagePositive = QtWidgets.QLabel(self.centralwidget)
        self.labelImagePositive.setGeometry(QtCore.QRect(360, 330, 121, 121))
        self.labelImagePositive.setText("")
        self.labelImagePositive.setPixmap(QtGui.QPixmap("957e806e153ab4f3cdf21b7c366bfdfb.png"))
        self.labelImagePositive.setScaledContents(True)
        self.labelImagePositive.setObjectName("labelImagePositive")
        self.labelUCTLogo.raise_()
        self.lablelTextMostCommon.raise_()
        self.pushButtonNeutral.raise_()
        self.pushButtonNegative.raise_()
        self.labelImageNegative.raise_()
        self.labelImageNeutral.raise_()
        self.labelImagePositive.raise_()
        self.pushButtonPositive.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bar Graph"))
        self.lablelTextMostCommon.setText(_translate("MainWindow",
                                                     "<html><head/><body><p><span style=\" font-size:16pt; color:#00007f;\">Bar graph for 10 most common words</span></p></body></html>"))
        self.pushButtonPositive.setText(_translate("MainWindow", "Positive"))
        self.pushButtonNeutral.setText(_translate("MainWindow", "Neutral"))
        self.pushButtonNegative.setText(_translate("MainWindow", "Negative"))

        # Button clicks call methods
        self.pushButtonPositive.clicked.connect(self.positive)
        self.pushButtonNeutral.clicked.connect(self.neutral)
        self.pushButtonNegative.clicked.connect(self.negative)

    def positive(self):
        textFile = "PositiveText.txt"
        ob.enter_file(textFile)
        ob.stopwords()

    def neutral(self):
        textFile = "NeutralText.txt"
        ob.enter_file(textFile)
        ob.stopwords()

    def negative(self):
        textFile = "NegativeText.txt"
        ob.enter_file(textFile)
        ob.stopwords()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BarGraph = QtWidgets.QMainWindow()
    ui = Ui_BarGraph()
    ui.setup(BarGraph)
    BarGraph.show()
    sys.exit(app.exec_())
