# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MonthPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import SQLiteDBModified

db = SQLiteDBModified.SQLDbModified()

from articlePage import *


class Ui_Monthly(object):
    def setupMonthly(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UCTTLogo = QtWidgets.QLabel(self.centralwidget)
        self.UCTTLogo.setGeometry(QtCore.QRect(20, 10, 541, 141))
        self.UCTTLogo.setText("")
        self.UCTTLogo.setPixmap(QtGui.QPixmap("uct_original_logo.jpg"))
        self.UCTTLogo.setObjectName("UCTTLogo")
        self.pushButtonJan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonJan.setGeometry(QtCore.QRect(30, 230, 131, 71))
        self.pushButtonJan.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonJan.setObjectName("pushButtonJan")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 170, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonFeb = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFeb.setGeometry(QtCore.QRect(190, 230, 131, 71))
        self.pushButtonFeb.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonFeb.setObjectName("pushButtonFeb")
        self.pushButtonSeptember = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSeptember.setGeometry(QtCore.QRect(350, 420, 131, 71))
        self.pushButtonSeptember.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonSeptember.setObjectName("pushButtonSeptember")
        self.pushButtonMay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMay.setGeometry(QtCore.QRect(190, 320, 131, 71))
        self.pushButtonMay.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonMay.setObjectName("pushButtonMay")
        self.pushButtonJune = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonJune.setGeometry(QtCore.QRect(350, 320, 131, 71))
        self.pushButtonJune.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonJune.setObjectName("pushButtonJune")
        self.pushButtonAugust = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAugust.setGeometry(QtCore.QRect(190, 420, 131, 71))
        self.pushButtonAugust.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonAugust.setObjectName("pushButtonAugust")
        self.pushButtonJuly = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonJuly.setGeometry(QtCore.QRect(30, 420, 131, 71))
        self.pushButtonJuly.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonJuly.setObjectName("pushButtonJuly")
        self.pushButtonApril = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonApril.setGeometry(QtCore.QRect(30, 320, 131, 71))
        self.pushButtonApril.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonApril.setObjectName("pushButtonApril")
        self.pushButtonMarch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMarch.setGeometry(QtCore.QRect(350, 230, 131, 71))
        self.pushButtonMarch.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonMarch.setObjectName("pushButtonMarch")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonJan.setText(_translate("MainWindow", "January"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:11pt; color:#0000ff;\">Please select a month for which you want sentiment analysis</span></p></body></html>"))
        self.pushButtonFeb.setText(_translate("MainWindow", "February"))
        self.pushButtonSeptember.setText(_translate("MainWindow", "September"))
        self.pushButtonMay.setText(_translate("MainWindow", "May"))
        self.pushButtonJune.setText(_translate("MainWindow", "June"))
        self.pushButtonAugust.setText(_translate("MainWindow", "August"))
        self.pushButtonJuly.setText(_translate("MainWindow", "July"))
        self.pushButtonApril.setText(_translate("MainWindow", "April"))
        self.pushButtonMarch.setText(_translate("MainWindow", "March"))

        self.pushButtonJan.clicked.connect(self.JanBarGraph)
        self.pushButtonFeb.clicked.connect(self.FebBarGraph)
        self.pushButtonMarch.clicked.connect(self.MarchBarGraph)
        self.pushButtonApril.clicked.connect(self.AprilBarGraph)
        self.pushButtonMay.clicked.connect(self.MayBarGraph)
        self.pushButtonJune.clicked.connect(self.JuneBarGraph)
        self.pushButtonJuly.clicked.connect(self.JulyBarGraph)
        self.pushButtonAugust.clicked.connect(self.AugustBarGraph)
        self.pushButtonSeptember.clicked.connect(self.SeptemberBarGraph)

    # This method will be called to go to the Article Page
    def newWindow(self, month):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Article()
        self.ui.setupArticle(self.window, month)
        self.window.show()

    def JanBarGraph(self):
        db.individualBarGraph('january_description')
        self.newWindow('january_description')

    def FebBarGraph(self):
        db.individualBarGraph('february_description')
        self.newWindow('february_description')

    def MarchBarGraph(self):
        db.individualBarGraph('march_description')
        self.newWindow('march_description')

    def AprilBarGraph(self):
        db.individualBarGraph('april_description')
        self.newWindow('april_description')

    def MayBarGraph(self):
        db.individualBarGraph('may_description')
        self.newWindow('may_description')

    def JuneBarGraph(self):
        db.individualBarGraph('june_description')
        self.newWindow('june_description')

    def JulyBarGraph(self):
        db.individualBarGraph('july_description')
        self.newWindow('july_description')

    def AugustBarGraph(self):
        db.individualBarGraph('august_description')
        self.newWindow('august_description')

    def SeptemberBarGraph(self):
        db.individualBarGraph('september_description')
        self.newWindow('september_description')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Monthly()
    ui.setupMonthly(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())