# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sentencesPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import SQLiteDBModified

db = SQLiteDBModified.SQLDbModified()


class Ui_sentences(object):
    def setupSentences(self, MainWindow, title, month):
        self.curr_title = title
        self.month = month
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UCTTLogo = QtWidgets.QLabel(self.centralwidget)
        self.UCTTLogo.setGeometry(QtCore.QRect(140, -10, 671, 211))
        self.UCTTLogo.setText("")
        self.UCTTLogo.setPixmap(QtGui.QPixmap("images/uct_original_logo.jpg"))
        self.UCTTLogo.setObjectName("UCTTLogo")
        self.pushButtonPositive = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPositive.setGeometry(QtCore.QRect(150, 620, 201, 91))
        self.pushButtonPositive.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonPositive.setObjectName("pushButtonPositive")
        self.pushButtonNegative = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNegative.setGeometry(QtCore.QRect(390, 620, 211, 91))
        self.pushButtonNegative.setStyleSheet("font: 75 12pt \"Cambria\";")
        self.pushButtonNegative.setObjectName("pushButtonNegative")
        self.textField = QtWidgets.QTextEdit(self.centralwidget)
        self.textField.setGeometry(QtCore.QRect(20, 250, 701, 351))
        self.textField.setObjectName("textField")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(30, 210, 721, 31))
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonPositive.setText(_translate("MainWindow", "Positive"))
        self.pushButtonNegative.setText(_translate("MainWindow", "Negative"))
        self.title.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:12pt; color:#00007f;\"></span></p></body></html>"))
        self.title.setText(self.curr_title)

        self.pushButtonPositive.clicked.connect(self.positive)
        self.pushButtonNegative.clicked.connect(self.negative)

    def positive(self):
        print(self.month)
        print(self.curr_title)
        result = db.getPositiveSentences(self.curr_title, self.month)
        self.textField.clear()
        self.textField.insertPlainText(result)

    def negative(self):
        result = db.getNegativeSentences(self.curr_title, self.month)
        self.textField.clear()
        self.textField.insertPlainText(result)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_sentences()
    ui.setupSentences(MainWindow, 'ABC', 'JAN')
    MainWindow.show()
    sys.exit(app.exec_())